pipeline:
  identifier: Build_aruntomsan_micro_svc_test_1770111775713
  name: Build micro-svc-test
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1770111652237
        repoName: aruntomsan/micro-svc-test
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo Starting dis shit
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: apptdockerconnect
                    region: ap-south-1
                    account: "014498640594"
                    imageName: " dev-appointment"
                    tags:
                      - version
                    dockerfile: appointment/dockerfile
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
