name: Build Appointment Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'appointment/**'

env:
  AWS_REGION: ap-south-1                 
  ECR_REGISTRY: 014498640594.dkr.ecr.ap-south-1.amazonaws.com
  REPO_NAME: dev-dev-ecr-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./appointment
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/${{ env.REPO_NAME }}:latest